spring:
  application:
    name: logibase
  datasource:
    url: jdbc:mysql://localhost:3306/logi_base
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  signerKey: "dd0mF6sjBcTq9fFm+BJQWi+qNP7SoUEvKq4tU5y4rdDL8a2ACdxpKzhgInuTJeUL"