spring:
  application:
    name: logibase
  datasource:
    url: jdbc:mysql://localhost:3306/logi_base
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  